### ISSUE TITLE
JSON export should be in V4 format

### ISSUE THREAD

**Issue by eMerzh** [i18next/i18next-gettext-converter#105]
## 🐛 Bug Report

Converted JSON Format is not compatible with I18Nnext any more

seems that the format has changed in v21.0.0, and the format used is V3... we need to support V4 now

## To Reproduce

compile po to json (with plurals ... the main diff)

## Expected behavior

V4 format is used :)

**Comment by perrin4869** [comment]
A PR would be very very helpful :)

**Comment by perrin4869** [comment]
Maybe we could collaborate to factor out the common parts into a common lib to reduce duplicate efforts? Not sure if that would make sense though

**Comment by perrin4869** [comment]
@eMerzh Released in `v11`!

**Comment by eMerzh** [comment]
thanks, @perrin4869  👏 
I'll test that soon
