### ISSUE TITLE
Plurals generation from .po for language with no plurals

### ISSUE THREAD

**Issue by pierrebaronqumu** [i18next/i18next-gettext-converter#143]
## 🐛 Bug Report

Hi,

I am using this tool to generate locales in multiple languages. My source files are `.po` files that I transform into `.json` files. Everything works fine for most languages but I noticed that the plural forms are not working correctly if the language does not have any plural forms (like Japanese)

I receive the `.po` files from a translation tool and I, therefore, do not want to transform them.

## To Reproduce

here is my .po file for English
```js
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

msgid "my_string"
msgid_plural "my_string"
msgstr[0] "{{count}} foo"
msgstr[0] "{{count}} bar"

```

here is my .po file for Japanse

```js
"Plural-Forms: nplurals=1; plural=0;\n"

msgid "my_string"
msgid_plural "my_string"
msgstr[0] "{{count}} foo"
```

## Expected behavior

I should expect the following JSON for English -> OK

```js
{
  "my_string": "{{count}} foo"
  "my_string_plural": "{{count}} bar"
}
```

I should expect the following JSON for Japanese

```js
{
  "my_string": "{{count}} foo"
}
```

Here is what I receive for Japanese

```js
{
  "my_string_0": "{{count}} foo"
}
```

While we can argue that Japanese should not use the plural form, I tested several translations platforms and they all return that format so I think we should support it.

**Comment by pierrebaronqumu** [comment]
Closing as it should be in this repo https://github.com/locize/gettext-converter/issues/5

**Comment by jamuhl** [comment]
Looking at i18next (v3 plurals) it uses the _0 suffix for "plurals" in those languages: https://jsfiddle.net/6bpxsgd4
