### ISSUE TITLE
Wrong conversion .po to .json

### ISSUE THREAD

**Issue by gabbosam** [i18next/i18next-gettext-converter#17]
Hi,
i have this situation:
my .po file contains something like that '\303\250' ('è' in Italian language), and when i convert the .po file into json its contains something like that '303250'...the backslash was ignored.
While when i try to convert .mo file (generated by msgfmt python module) to .json is correct and in the output file i found 'è'.

Bye
Gabriele

**Comment by rahuljal** [comment]
Can some one help me on how to convert .po file to .json file?

I am getting below error,

C:\windows\system32>po2json --errorlevel traceback  frr.po  frr.json
processing 1 files...

po2json: warning: Couldn't handle input file frr.po: Traceback (most recent call
 last):

  File "translate\misc\optrecurse.pyc", line 513, in recursiveprocess

  File "translate\misc\optrecurse.pyc", line 417, in getoutputoptions

ValueError: don't know what to do with input format .po, no template file

**Comment by jamuhl** [comment]
closing for now...
