### ISSUE TITLE
Unble to convert .po file to .json (gettext).

### ISSUE THREAD

**Issue by rahuljal** [i18next/i18next-gettext-converter#19]
I have installed po2json using 
npm install po2json

I am getting below error,

C:\windows\system32>po2json --errorlevel traceback  fr.po  fr.json
processing 1 files...

po2json: warning: Couldn't handle input file fr.po: Traceback (most recent call
 last):

  File "translate\misc\optrecurse.pyc", line 513, in recursiveprocess

  File "translate\misc\optrecurse.pyc", line 417, in getoutputoptions

ValueError: don't know what to do with input format .po, no template file
===================================================================
where as my fr.po file is

# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: \n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-03-23 22:15+0530\n"
"PO-Revision-Date: 2015-03-23 22:21+0530\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Last-Translator: \n"
"Language-Team: \n"
"X-Generator: Poedit 1.7.4\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"
"Language: fr\n"

#: text.js:794
msgid "Search Files"
msgstr "Search Files FRENCH"

===================================================================

**Comment by jamuhl** [comment]
can't help much....you ever tried on a linux machine to make sure it's not an issue that this in general does not work under windows...

**Comment by marisradu** [comment]
Not a linux issue, but I guess not your issue either as I've got the exact same error (same file and line on backtrace) using the translation-toolkit's po2json under Ubuntu 12.04.

**Comment by jamuhl** [comment]
closing for now...
