### ISSUE TITLE
Source (original text) as msgid, msgstr as translaiton, jsonkey as msgctxt

### ISSUE THREAD

**Issue by alisman** [i18next/i18next-gettext-converter#20]
Converting from i18next json format to gettext, i see that you are using the json key as the msgid.   This doesn't in line with gettext standard (https://www.gnu.org/software/gettext/manual/gettext.html#Files), which is to use the original string as the msgid and the string's key in the msgctxt. 

Was there a reason to do it this way?

**Comment by jamuhl** [comment]
the reason was that i expected the keys to be mgsids...so converting from gettext to json would use msgid as key.

**Comment by alisman** [comment]
Hi Jamuhl, 
I work for Smartling.  Our clients want to use your converter to from i18next format to gettext, a format our api supports.  The trouble is, we require gettext msgids to be source string, not key.  This is actually consistent with the spec.   

Would you be open to (we'll do the work) either creating a param to force output of gettext in this way or adding a filter that would allow us to monkey with the gettext before it's printed?  The current filter mechanism doesn't seem to work when going from i18next to gettext.  (it may actually be broken altogether, not sure, but i get error when i specify it)

**Comment by jamuhl** [comment]
sorry missed this one...sure...PR's are more then welcome...even complete rewrite...

**Comment by jamuhl** [comment]
should be solved by: https://github.com/i18next/i18next-gettext-converter/pull/41
