### ISSUE TITLE
ignore fuzzy entries

### ISSUE THREAD

**Issue by bantidisturbis** [i18next/i18next-gettext-converter#21]
Hi, is it possible to convert from .po to json ignoring fuzzy entries?

Thanks

**Comment by jamuhl** [comment]
basically this just wraps 'node-gettext'. so if it's possible there it will be possible.

any PR solving your demand could be merged and published. as i myself do not use this project on my personal projects i can't invest more time on this. so only your contribution will make this land.

**Comment by jamuhl** [comment]
closing for now...PR still welcome
