### ISSUE TITLE
How I can run it from node environment?

### ISSUE THREAD

**Issue by max-mykhailenko** [i18next/i18next-gettext-converter#22]
I don't want use command line interface. How I can run converter from node environment?

**Comment by jamuhl** [comment]
var converter = require('i18next-conv');
converter. ...

see eg: https://github.com/i18next/i18next-gettext-converter/blob/master/test/gettextWrapper.test.js#L111

**Comment by max-mykhailenko** [comment]
@jamuhl what about `json` to `mo` file converting?

**Comment by jamuhl** [comment]
depends on the ending of target: https://github.com/i18next/i18next-gettext-converter/blob/master/lib/gettextWrapper.js#L72

**Comment by max-mykhailenko** [comment]
@jamuhl Thanks, I will try it soon!
