### ISSUE TITLE
Generate nested JSON from .po

### ISSUE THREAD

**Issue by paulblyth** [i18next/i18next-gettext-converter#23]
Hey!

Given the following .po key:message structure:

```
msgid "app.module.key"
msgstr "Some translated content"
```

I want to generate a JSON file in a format like so:

```json
{
    "app": {
        "module": {
            "key": "Some translated content"
        }
    }
}
```

Is this possible?

Cheers,
Paul

**Comment by jamuhl** [comment]
this is what this project is used for...

**Comment by paulblyth** [comment]
Ok.. I'm obviously doing something wrong :sweat_smile: 

I end up with JSON that looks like:

```json
{
    "app.module.key": "Some translated content"
}
```

**Comment by paulblyth** [comment]
A-ha!

Found the --keyseparator flag!
