### ISSUE TITLE
Google Translation Toolkit and Poedit

### ISSUE THREAD

**Issue by robjens** [i18next/i18next-gettext-converter#25]
Two renowned solutions I guess, that both take `.po` files yet choke on the output generated by this tool. Am I doing something wrong? Is this a different format? Google says "Document does not have translatable content" and Poedit complains "File cannot be opened".

Obviously adding "UTF" takes/text as mentioned in the README doesn't work. The entire header of the document is garbled/binary and dumping a plain text line like that is likely not what is required.

Please advice

**Comment by jamuhl** [comment]
no idea...depending on node-gettext for parsing and compiling. but honestly the used dependency is outdated and should be replaced with https://github.com/andris9/gettext-parser.

not sure that would solve the issue...and as i'm currently focusing on i18next v2.0.0 won't get to this very soon.

PR would be very welcome to solve your issue.

**Comment by jamuhl** [comment]
2.3.0 updated to gettext parser..no idea if better now...closing...but feel free to reopen or providing a PR if still having issues.
