### ISSUE TITLE
json to po conversion is written as a mo file instead with 0.1.5

### ISSUE THREAD

**Issue by stephenash** [i18next/i18next-gettext-converter#26]
With `i18next-conv@0.1.5`, I am seeing `.po` files written with the `.mo` file format instead. `i18next-conv@0.1.4` did not have this problem.

```shell
$ npm install i18next-conv@0.1.4
$ ./node_modules/.bin/i18next-conv --quiet -l en -s sample.json -t output-0.1.4.po
$ head -1 output-0.1.4.po
msgid ""

$ npm install i18next-conv@0.1.5
$ ./node_modules/.bin/i18next-conv --quiet -l en -s sample.json -t output-0.1.5.po
$ head -1 output-0.1.5.po
??,,<=?C?HelloProject-Id-Version: node-gettext
```

Sample files and output: https://gist.github.com/stephenash/caac6f17c878589ee5b9

**Comment by jamuhl** [comment]
only commit from 0.1.4 to 0.1.5 is https://github.com/i18next/i18next-gettext-converter/commit/8807e6dc703973628cad15f15fd9302431494a73

i don't see how this should affect it....
