### ISSUE TITLE
Undefined is not a function

### ISSUE THREAD

**Issue by RDeluxe** [i18next/i18next-gettext-converter#28]
Hi,

I've played a bit with i18next and had no problem with json. I tried with po/mo files and got a weird error, which does not seem to be linked to my files.
I don't know where this is coming from. I'm running Node under windows.

```javascript
TypeError: undefined is not a function
    at c:\Users\Deluxe\Dropbox\Moi\Job\CityinvadersCode\cityinvaders-server\node_modules\i18next.gettext\node_modules\i18next-conv\lib\gettextWrapper.js:242:5
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
```

I checked with the debugger, and it seems my keys are correctly readed.

**Comment by RDeluxe** [comment]
Ok, found it.

In sync.js, line 14 and 21, the options parameter is missing.

I corrected quickly by adding empty options !

Hard to believe this could have been tested guys :)

```javascript
    fetchOne: function(lng, ns, callback) {
        var source = this.functions.applyReplacement(this.options.resGetPath, {lng: lng, ns: ns});

        var self = this;
        converter.addTextDomain(lng, source, {}, function(err, data) {
            // console.log(data);
            if (err) {
                callback(err);
                return;
            } 

            converter.parseJSON(lng, data, {}, function(err, json) {
                if (err) {
                    callback(err);
                } else {
                    self.functions.log('loaded file: ' + source);
                    callback(null, json);
                }
            });
        });
    }
```

**Comment by jamuhl** [comment]
that's one of the problems i got with i18next. it started with my own need for some simple solution to get translations in node.js and on clientside. ended in what i18next is today. as i started on i18next v2 a few weeks ago i can see the size of it - all the ecosystem around it. hard to maintain this by myself - even harder to find people interested in contributing on longterm.

as i myself does not use gettext (mo/po) it's more or less purely depending on commits and feedback from the community. and yes your right...that backend was not tested (and seems no one used it - cause of the error - or demand). there are people using the converter as is.

will fix this asap and publish an updated version to npm. thanks a lot for the finding.

**Comment by RDeluxe** [comment]
I totally understand. I thought there was a team behind the project.

Thing is, we needed something to handle translations on the server side (Node) and compatible with Jade templates (Express + Jade). The only problem I see with i18next in its current form is that it's hardly compatible with po files, which are the industry standard. 
We are currently looking into easy solution for outsourcing the translation of our game and website, and most tools are based on pot/po (I'm testing poeditor.com which looks like a neat website). Translators woudn't know how to modify json files correctly.

I had another problem which I found weird, not sure if it's a bug though. Any way I could ask you in PM about it to avoid spamming here ? (it's really nothing)

**Comment by jamuhl** [comment]
sure you can PM me. jan.muehlemann@gmail.com

personally never had the need for po files...but would be great to see that proper working in i18next.

**Comment by jamuhl** [comment]
added your fix and published new gettext backend for good old i18next v1.11.x
