### ISSUE TITLE
Convert all .po files in directory

### ISSUE THREAD

**Issue by jacobrask** [i18next/i18next-gettext-converter#29]
I have a suggestion to simplify batch processing of translations.

Given the files

```
translations/en-US.po
translations/sv-SE.po
```

`i18next-conv -s translations/` should generate

```
locales/en-US/translation.json
locales/sv-SE/translation.json
```

**Comment by jamuhl** [comment]
PR would be welcome...as i'm hard on time for implementing this...but

https://github.com/i18next/i18next-gettext-converter/pull/24

should be all needed to write a gulp or grunt task doing this...not sure if batch processing should be the needed in this...but won't hurt...so i would accept a PR

**Comment by perrin4869** [comment]
I actually made a gulp task to accomplish this, give me a few hours and put up a sample how you can do this!

**Comment by perrin4869** [comment]
OK I finally got around to writing documentation for my gulp plugin, check here the example how you can do the conversion automatically!
https://github.com/perrin4869/gulp-i18next-conv
I would still need to add tests and maybe more customization, not sure when I'll get around to doing that though

**Comment by jamuhl** [comment]
great to see the progress...and yes...always hard to find time for doing such things.

**Comment by jacobrask** [comment]
Thanks!
