### ISSUE TITLE
Plural & singular form are flipped when PO -> JSON

### ISSUE THREAD

**Issue by chung0607** [i18next/i18next-gettext-converter#33]
```
msgid "a##apple"
msgid_plural "a##apple"
msgstr[0] "I have an apple"
msgstr[1] "I have {count} apples"
```
become
```
    "a": {
        "apple_plural": "I have an apple",
        "apple": "I have {count} apples",
        "apple_negative": "I have no apples"
    },
```
After conversion.

**Comment by jamuhl** [comment]
strange:

test: https://github.com/i18next/i18next-gettext-converter/blob/master/test/gettextWrapper.test.js#L67

https://github.com/i18next/i18next-gettext-converter/blob/master/test/_testfiles/en/translation.utf8.po
```
msgid "a##apple"
msgid_plural "a##apple"
msgstr[0] "I have an apple"
msgstr[1] "I have {count} apples"
```

tests against:

https://github.com/i18next/i18next-gettext-converter/blob/master/test/_testfiles/en/translation.utf8.json
```
    "a": {
        "apple": "I have an apple",
        "apple_plural": "I have {count} apples",
        "apple_negative": "I have no apples"
    },
```

can you revalidate this:

```
npm install
mocha
```

**Comment by chung0607** [comment]
Thanks for your help.

I use the locale `en_us` from my gettext po file for the `--language` parameter. I guess it cannot get the right plural forms and cause the problem.

Hope the plural form resolver can be more tolerable to gettext style locale.

**Comment by jamuhl** [comment]
hm...plural will be based on `en` but i'm rather sure the code splits language-region by `-` not by `_` => `en-US` instead of `en_us`.

**Comment by jamuhl** [comment]
rather sure caused here: https://github.com/i18next/i18next-gettext-converter/blob/master/lib/plurals.js#L1072

a PR would be welcome to make this configurable....
