### ISSUE TITLE
Newlines in msgstr are wrongly converted to .json

### ISSUE THREAD

**Issue by VilmaRamos** [i18next/i18next-gettext-converter#35]
The problem occurs when there's a msgstr that end with a newline. For instance, when my .po file contains:

```
msgid "key"
msgstr "My string.\n"
```

When I try to convert from .po to .json, I'm expecting the following output

```
        "key": "My string."
```
but instead I'm getting

```
        "key": [
            "My string.",
            ""
        ]
```
Can you trim the strings before conversion?

Thanks!

**Comment by jamuhl** [comment]
right...should not be that way by default when using v2 of i18next. thanks for reporting.

should be fixed in v2.1.1
