### ISSUE TITLE
Stream support?

### ISSUE THREAD

**Issue by megapctr** [i18next/i18next-gettext-converter#38]
It would be awesome if this library accepted vinyl streams as sources. Then we could pass it the results from [i18next-parser](https://github.com/i18next/i18next-parser) without creating partial result directories

**Comment by jamuhl** [comment]
right now i am to short on time for looking into this. feel free to create a pr.

**Comment by megapctr** [comment]
As a temporary workaround, I'm storing the results in a temp dir via [node-temp](https://github.com/bruce/node-temp).

**Comment by perrin4869** [comment]
Not entirely sure what it is you can do, but you can take a look at my [gulp-i18next-conv](https://github.com/perrin4869/gulp-i18next-conv) plugin for hints of how to use vinyl files with this module. Basically the new API just released allows you to do anything you want :)

**Comment by megapctr** [comment]
Great, thanks. I think we can close this
