### ISSUE TITLE
Reverse generating problem

### ISSUE THREAD

**Issue by max-mykhailenko** [i18next/i18next-gettext-converter#43]
Generated `mo` file doesn't work with php gettext and I try to test it. I generate `mo` file with node `converter.i18nextToGettext(languages[lng], source, target, options, callback);`. After that I trying to generate `json` from this `mo` and got this

```
> node build/json.js

undefined:1
��
^

SyntaxError: Unexpected token �
    at Object.parse (native)
    at /tmp/node_modules/i18next-conv/lib/gettextWrapper.js:126:45
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)

npm info lifecycle rgb-lab.net@3.0.0~json: Failed to exec json script
npm ERR! Linux 4.1.19-boot2docker
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "json"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! rgb-lab.net@3.0.0 json: `node build/json.js`
npm ERR! Exit status 1
```

How I can debug `mo` in another way or fix this issue?

**Comment by jamuhl** [comment]
no idea - basically we use https://github.com/andris9/gettext-parser and there seems not to be an issue for that...and we're on the latest version.

no idea...most tests here go for po files - only one for mo

**Comment by perrin4869** [comment]
I imagine this problem has been solved by upgrading `gettext-parser` and the new `gettextDefaultCharset` option - please reopen if this is still an issue
