### ISSUE TITLE
Untranslated entries are converted to empty strings

### ISSUE THREAD

**Issue by pvenakis** [i18next/i18next-gettext-converter#44]
Hi, it seems that if I run i18next-conv on a .po file that has some untranslated entries, it will produce a json where the translation part is empty. This will make i18next to translate to an empty string. Is there a way to skip untranslated entries from being placed into the resulting json (so I can use the fallback methods provided by i18next)?

**Comment by jamuhl** [comment]
no - there is no such option in i18next-conv right now - PR would be welcome

as a work around you can set returnEmptyString to false on i18next init.

**Comment by perrin4869** [comment]
Implemented as `skipUntranslated`, will make a release later!

**Comment by pvenakis** [comment]
awesome, thanks!

**Comment by perrin4869** [comment]
Released just now :)
