### ISSUE TITLE
Expose programmatic interface

### ISSUE THREAD

**Issue by queicherius** [i18next/i18next-gettext-converter#47]
It would be neat if we could convert things into each other without requiring the files to exist as a necessity. I made a (pretty hacky) fork for it [here](https://github.com/i18next/i18next-gettext-converter/commit/5b733deaf27416494bfface453467b00b9491046#diff-168726dbe96b3ce427e7fedce31bb0bc), but I would appreciate this functionality in the main module. :)

If you would like to get a PR for this, let me know.

--

<sub>Also on a sidenote, the docs + code formatting could use some work, I'd put up a PR for that too if you like</sub>

**Comment by jamuhl** [comment]
PR's are very welcome. As i don't use this module personally it's hard to get it better without the help of the community...so feel free

**Comment by perrin4869** [comment]
I did part of the refactoring a few months ago when I wrote `gulp-i18next-conv` plugin actually.
But yeah this repo needs serious refactoring, there are portions where the indentation is in tabs and others in spaces... probably should setup eslint here. I would like to help here too.
Another thing, the `quite` option, which is false by default, should be changed in favor of a `verbose` option, which is turned off by default, to be more consistent with other interfaces. By default it should not output messages during conversion.

**Comment by jamuhl** [comment]
if someone really is interested in this...i be open to hand over this repos admin rights and npm publish ownership

**Comment by jamuhl** [comment]
else any PR will be merged and published....what you prefer is ok for me

**Comment by perrin4869** [comment]
Sure, I'll take you up on that offer, might have time to re-work this repo during the weekend.
My current plans are to replace the `quite` option with `verbose`, refactor into a programmatic API, and install airbnb eslint config.

**Comment by perrin4869** [comment]
@jamuhl I think it might be a good idea to separate the cli into a separate repository, `i18next-gettext-converter-cli`, and npm package, `i18next-conv-cli`, and have this library here be just the API. Babel does something similar with `babel-core` and `babel-cli`, etc. Any thoughts?

**Comment by jamuhl** [comment]
@perrin4869 personally i think its a little overengineered looking the size of converter...just exposing `bin` and `main` seems ok for me...but if you prefer we could add another repo...

**Comment by perrin4869** [comment]
Hm... the reason I want to do this, is actually that the bin file has es6 which need to be transpiled... and I'm not sure where to put the source for that. The cleanest solution is to have a separate repo for the CLI... although that is slightly more work to complete. Any better ideas?

**Comment by queicherius** [comment]
Let's say you transpile the code from `src/bin.js` and `src/interface.js` into `dist/`, then you can just do the following:

```js
// package.json
{
  "main": "dist/interface.js",
  "bin": {"i18next-gettext-converter": "dist/bin.js"}
}
```

That way you can transpile all the code, have the binary as you are used to, and can require the interface as expected:

```bash
i18net-gettext-converter --some --options # -> will resolve to dist/bin.js
```

```js
var interface = require('i18net-gettext-converter') // -> will resolve to dist/interface.js
```

**Comment by perrin4869** [comment]
@queicherius well yeah, that's a solution, but the perfectionist in me doesn't wanna put the `bin.js` into `src`, with all the API related files... I feel like it should be separate... although I might just go down that route since it's the easiest

**Comment by queicherius** [comment]
I am used to just making subfolders in the `src` directory like `src/api/...` and `src/bin/...` :smile:

**Comment by jamuhl** [comment]
just let me know if you need an additional repo...both variants have it ups and downs

**Comment by perrin4869** [comment]
I ended up going with the solution proposed by @queicherius 
Just finished exposing the API now! It's a promise based API. Tell me what you think about it, if it's good we can close this issue :)

**Comment by queicherius** [comment]
The interface looks good! 👍
