### ISSUE TITLE
Plural numbers

### ISSUE THREAD

**Issue by perrin4869** [i18next/i18next-gettext-converter#52]
@jamuhl In the [plurals](https://github.com/i18next/i18next-gettext-converter/blob/master/src/lib/plurals.js) file you have an array of numbers, which doesn't seem to be used at alll except for its length. Do you know if it is safe to remove then? What was it used for?

**Comment by jamuhl** [comment]
was used for plurals in pre v3 i18next: http://i18next.com/docs/jsons/

pre v3 the number was used as suffix, now the index is taken like in gettext.

**Comment by perrin4869** [comment]
Cool, thanks for confirming! Removed the arrays since they are redundant.
