### ISSUE TITLE
Deprecate filter option

### ISSUE THREAD

**Issue by perrin4869** [i18next/i18next-gettext-converter#61]
I don't see the value of having filter in the core library, since you could actually filter the translations yourself after completion...
Any opinions @jamuhl?

**Comment by perrin4869** [comment]
ok I see a possible use like "filtering by comment" which would be lost otherwise

**Comment by jamuhl** [comment]
@perrin4869 not sure - but i believe this was added later to the mix (or at least i can't remember that).
