### ISSUE TITLE
CLI Problems

### ISSUE THREAD

**Issue by delphiactual** [i18next/i18next-gettext-converter#62]
-ks does not work as an option, error produced: `error: unknown option '-k'`
--keyseparator works as intended.

--project stops all processing https://github.com/i18next/i18next-gettext-converter/issues/57#issuecomment-310316386

i18next-conv: `4.0.1`

**Comment by perrin4869** [comment]
will take a look at this during the weekend! If you can send a PR it'll be a huge help!

**Comment by perrin4869** [comment]
changed -ks option to -k in 4.0.3, tell me if there are any remaining problems!
