### ISSUE TITLE
i18next variable interpolation

### ISSUE THREAD

**Issue by siavashkavousi** [i18next/i18next-gettext-converter#63]
I convert my .po file using this lib but I have problem using interpolation in i18next.

for example my .po file is:
```
  msgid: "Date: {date}"
  msgstr: "foo: {date}"
```

I use it like this `i18next.t('Date: {date}', {date: '2017/2/2'})` but it doesn't work.

**Comment by jamuhl** [comment]
formatting format is like https://www.i18next.com/formatting.html

**Comment by siavashkavousi** [comment]
But it's not working...
I use it like this `i18next.t('Date: {date}', {date: '2017/2/2'})`
but it's not working

**Comment by jamuhl** [comment]
`i18next.t('Date: {{date}}', {date: '2017/2/2'})` -> doube `{{` ... `}}`

**Comment by jamuhl** [comment]
or change the settings for prefix/suffix on init call: https://www.i18next.com/interpolation.html#all-interpolation-options

**Comment by siavashkavousi** [comment]
output json is:
![screenshot from 2017-06-27 14-54-19](https://user-images.githubusercontent.com/11883216/27583104-8ae99776-5b48-11e7-8d44-d7ed5260ceaa.png)
I've used what you say and it worked but it's a different key from what I have in my translation file.

**Comment by jamuhl** [comment]
msgid: "Date: {date}"
  msgstr: "foo: {date}"

-> key: "Date: {date}"

where is the difference...sorry do not see it

**Comment by siavashkavousi** [comment]
Sorry let me go into more details

assuming I have a translation .po file with the following content
```
  msgid: "Date: {date}"
  msgstr: "foo: {date}"
```
Then I convert it to .json using and .json file looks like:
```
  "Date: {date}": "foo: {date}"
```
and set i18next
```
i18next.init({
  lng: "fa",
  resources: {
    fa: {
      translation: require('somewhere/translation.json'),
    },
  },
  keySeparator: false,
  nsSeparator: false,
})
```

and at last in my app if I use it like this
```
  i18next.t('Date: {date}', {date: '2017/2/2'})
```
output will be 
```
  foo: {date}
```
w/o interpolating date and if use it like the following
```
  i18next.t('Date: {{date}}', {date: '2017/2/2'})
```
output will be 
```
  Date: 2017/2/2
```
w/o translating.

**Comment by jamuhl** [comment]
And i told you single `{` will not work on interpolation as default is `{{`

a) change that in your translation files
b) change the options like told in the provided link:

```js
i18next.init({
  lng: "fa",
  resources: {
    fa: {
      translation: require('somewhere/translation.json'),
    },
  },
  keySeparator: false,
  nsSeparator: false,
  interpolation: {
    prefix: '{',
    suffix: '}'
  }
})
```

**Comment by siavashkavousi** [comment]
Oh thanks I didn't see that message :sweat_smile: and I've tried an older syntax for interpolation options

didn't notice changes.
Thanks.

**Comment by siavashkavousi** [comment]
Sorry for reopening
The same example above if I want to unescape interpolated variable it doesn't get translated
```
  'Date: {- date}'
```

**Comment by jamuhl** [comment]
same: https://www.i18next.com/interpolation.html#all-interpolation-options

should work if you set the prefix/suffix correctly

**Comment by siavashkavousi** [comment]
It worked in escaped mode (without using dash)

**Comment by jamuhl** [comment]
Relevant is what is in your value...not what you write in the key.

`"Date: {date}": "foo: {- date}"`

**Comment by jamuhl** [comment]
if you change the key inside t it will not find translation.

**Comment by jamuhl** [comment]
alternatively you can do: i18next.t('Date: {date}', { date: '2017/2/2', escapeValue: false })

**Comment by siavashkavousi** [comment]
that's what I've done at the end :). Thanks a lot.
