### ISSUE TITLE
Could 'gettextToI18next' function be synchronous?

### ISSUE THREAD

**Issue by BusfyJan** [i18next/i18next-gettext-converter#70]
I would like to use this function in 'parse' function of 'backend' option of i18n.init({}) function, but 'parse' function cannot return Promise.

Something like this:

```javascript
import i18n from "i18next";
import XHR from "i18next-xhr-backend";
import { gettextToI18next } from "i18next-conv";

i18n.use(XHR).init({
    lng: "sk",
    fallbackLng: "sk",
    debug: process.env.REACT_APP_ENV === "development",
    ns: ["parameter", "parametervalue"],
    backend: {
        loadPath: "i18n/json/{{ns}}.{{lng}}.json",
        parse: data => {
            return gettextToI18next("sk", data, {});
        }
    }
});

export default i18n;
```

https://github.com/i18next/i18next-gettext-converter/blob/b49e88ccbcdecf5c342de1844aa944fbeb957a54/src/lib/gettext2json.js#L39

**Comment by jamuhl** [comment]
what backend implementation you use fs? that has no parse option only xhr for clientside has that if i remember right?!?

why not creating a own backend based on fs backend using gettext-converter? https://www.i18next.com/misc/creating-own-plugins.html#backend 

or did you already try: https://github.com/palamccc/i18next.gettext/

**Comment by perrin4869** [comment]
hm... I don't remember why I made it asynchronous, but I do agree with jamuhl, probably the best solution would be to make a custom backend.
I will consider this for the next major release though... whenever that may be...

**Comment by BusfyJan** [comment]
I use XHR backend implementation.
I wanted to use i18next.gettext as my backend, but I am not sure how to use it.

@jamuhl 
I wanted to use i18next.gettext as my backend, but I am not sure how to use it properly. Could you please provide me with some examples?

@perrin4869 
And what about adding custom option to enable synchronous resolving? Would that be possible as a minor release?

**Comment by perrin4869** [comment]
Hm... I could add a `gettextToI18nextSync` function I guess

**Comment by BusfyJan** [comment]
That would be great and would help me a lot 👍 
Do you need my help with that?

**Comment by perrin4869** [comment]
Yeah, I'd really appreciate it if you send me a PR with it :)

**Comment by jamuhl** [comment]
@BusfyJan don't think you can just use the xhr backend and directly load gettext files...you will need to convert those upfront or like said create a new node.js backend to make those conversions on the fly

**Comment by BusfyJan** [comment]
@jamuhl Yeah, but I need to be able to convert gettext files on the client, because I am not allowed to create node.js backend because I am working on pure frontend project 😒

**Comment by perrin4869** [comment]
@BusfyJan how about adding a conversion of `gettext -> json` step to your build process?

**Comment by BusfyJan** [comment]
@perrin4869 I have a conversion like that in my build step right now. But I wanted to avoid this step 😄  Do you think it is a better idea to convert .po -> .json as build step?

**Comment by jamuhl** [comment]
@BusfyJan for sure the idea of converting during build request is a lot better than on every client when loading the file (just out of performance that would not work well i think) -> do it during build time...

**Comment by perrin4869** [comment]
I do it in my own personal projects, so the answer is yes :)

**Comment by BusfyJan** [comment]
Okay guys, you have persuaded me 😄 
Thank you for your time and help. I will stick to the converting during build step.
We can close this issue 😄

**Comment by perrin4869** [comment]
I'll keep this open because I still wanna reevaluate whether or not the functions should be sync or async

**Comment by adrai** [comment]
This module can be used: https://github.com/locize/gettext-converter
