### ISSUE TITLE
Why "##" separator in generated translation keys in PO/MO?

### ISSUE THREAD

**Issue by meglio** [i18next/i18next-gettext-converter#76]
When converting the following JSON to a PO file:

```
{
  "signup": { "title": "Sign Up" }
}
```

Key generated is `signup##title`.

Why does it use `##` instead of a dot, and is there a way to adjust it?

**Comment by meglio** [comment]
UPD. I can see the `keyseparator ` option. But still, out of curiosity, why `##`? is there any standard or convention for this?

**Comment by jamuhl** [comment]
Not sure...on the time we created this it seemed to be a save bet to do so.

keySeparator might be only be used in the JSON not sure -> if not configurable you might create a PR todo so.

**Comment by meglio** [comment]
`--keyseparator` option did work. Thanks.
