### ISSUE TITLE
Nesting not supported ?

### ISSUE THREAD

**Issue by Heziode** [i18next/i18next-gettext-converter#93]
From [the doc](https://www.i18next.com/translation-function/nesting):

```json
{
    "nesting1": "1 $t(nesting2)",
    "nesting2": "2 $t(nesting3)",
    "nesting3": "3",
}
```

If I convert to gettext, I get something like this:

```gettext
msgid "nesting1"
msgstr "1 $t(nesting2)"

msgid "nesting2"
msgstr "2 $t(nesting3)"

msgid "nesting3"
msgstr "3"
```

**Comment by jamuhl** [comment]
That's what is expected...what do you expect?

**Comment by Heziode** [comment]
There is no nesting feature in GetText ?

Furthermore, path like this are not converted:
```json
{
   "info": "A message with $t(message.nesting.key) message"
}
```

Give something like this:

```gettext
msgid "info"
msgstr "A message with $t(message.nesting.key) message"
```

Instead of something like this:

```gettext
msgstr "A message with $t(message##nesting##key) message"
```

Or am I wrong?

**Comment by jamuhl** [comment]
This lib is not about making i18next and gettext compatible...it's using gettext fileformat with i18next

**Comment by Heziode** [comment]
Oh, right.

Do you know a lib for compatibility?

**Comment by jamuhl** [comment]
no...sorry not aware of any converting those from each other
