### ISSUE TITLE
Exported files missing Language field

### ISSUE THREAD

**Issue by rebeccaalpert** [i18next/i18next-gettext-converter#96]
## 🐛 Bug Report

i18nextToPo and i18nextToPot do not add the language to the header information in the exported file.

Our headers look something like this:
```
msgid ""
msgstr ""
"Project-Id-Version: i18next-conv\n"
"mime-version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0\n"
"POT-Creation-Date: 2020-10-28T18:25:17.432Z\n"
"PO-Revision-Date: 2020-10-28T18:25:17.432Z\n"
```

According to our translation team (and some earlier bug reporters), there should be a `"Language: ja\n"` field as well.

## To Reproduce

Our call looks like this: 
```js
i18nextToPo('ja', fs.readFileSync(file)).then(
      save(poFile)
    );
```

## Expected behavior

We would expect to see a `"Language: ja\n"` field in the header with the correct language (Japanese in this case).

## Your Environment

- *runtime version*: node 10.16.2
- *i18next version*: 10.0.2
- *os*: Mac

**Comment by jamuhl** [comment]
pull request welcome

**Comment by rebeccaalpert** [comment]
Cool, I'll look into it as I have time.

**Comment by adrai** [comment]
@rebeccaalpert You may try to call it like this: 

```javascript
i18nextToPo('ja', fs.readFileSync(file), { language: 'ja' }).then(
      save(poFile)
);
```
Or try a PR that takes the locale as fallback for the Language Field, like: https://github.com/locize/gettext-converter/blob/master/lib/i18next2po.js#L51

**Comment by rebeccaalpert** [comment]
Perfect. Thanks @adrai.
